<?php

use Illuminate\Database\Seeder;

class SugarTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('sugar_levels')->insert(
            $entries = [
                [
                    'value' => 7.8,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(3)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.8,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 9.1,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.2,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 10.4,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(7)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 5.7,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.2,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.5,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.7,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 3.7,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(2)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.5,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.5,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.2,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 5.9,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.0,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
                ], [
                    'value' => 8.3,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(32)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.0,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.7,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
                ], [
                    'value' => 8.5,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.8,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.3,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.5,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(7)->format('Y-m-d H:i:s'),
                ], [
                    'value' => 7.9,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ], [
                    'value' => 8.0,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
                ], [
                    'value' => 6.9,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.6,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(11)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.1,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(12)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.8,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(13)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.7,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(14)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.0,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(1)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 12.1,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(15)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.9,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(13)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 10.0,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(13)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.3,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(2)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.8,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(7)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 10.0,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 10.9,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.6,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 12.8,
                    'medicine_id' => null,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(3)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.9,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.4,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(7)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.5,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.8,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
                ], [
                    'value' => 5.6,
                    'medicine_id' => 1,
                    'exercise_id' => null,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(5)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.4,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(14)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 9.0,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(14)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.4,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(15)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.8,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(15)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 11.2,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(17)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.7,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(1)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.7,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(1)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.7,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(1)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 5.3,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.7,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(4)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 17.3,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => 3,
                    'created_at' => \Carbon\Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.5,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(8)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 9.6,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 10.7,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(15)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 13.5,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(6)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 14.0,
                    'medicine_id' => null,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(16)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.5,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(16)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 9.2,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(13)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 7.9,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(19)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 9.3,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(7)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 11.3,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(9)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 6.5,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
                ],
                [
                    'value' => 8.4,
                    'medicine_id' => 1,
                    'exercise_id' => 1,
                    'timeString_id' => App\Time::all()->random()->id,
                    'created_at' => \Carbon\Carbon::now()->subDays(10)->format('Y-m-d H:i:s'),
                ]

            ]
        );
    }
}
